apiVersion: v1
data:
  allow-snippet-annotations: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-system
    app.kubernetes.io/name: ingress-nginx-system
    app.kubernetes.io/part-of: ingress-nginx-system
    app.kubernetes.io/version: 1.5.1
  name: ingress-nginx-system-controller
  namespace: ingress-nginx-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx-system
  labels:
    app.kubernetes.io/name: ingress-nginx-system
    app.kubernetes.io/part-of: ingress-nginx-system
data:
  9001: "hyperauth/kafka-1:9093"
  9002: "hyperauth/kafka-2:9093"
  9003: "hyperauth/kafka-3:9093"
